### ISSUE TITLE
Import comments when importing from PGN file

### ISSUE THREAD

**Issue by tkozybski** [lukasmonk/lucaschessR#45]
In opening lines, when importing moves from a PGN file, the comments are skipped. Could you add an option to also import the comments?

**Comment by tkozybski** [comment]
@lukasmonk  tagging you in case you missed it. Would really appreciate this feature.

**Comment by lukasmonk** [comment]
Don't worry, I'm taking my time because I have to study it first, and I still have to reply to a message about studying which is taking me a long time. Besides, today stockfish 14 has been released and I have to update the program. As soon as I have code or I see that it's too complicated I'll answer you again.

**Comment by tkozybski** [comment]
Thank you for your response, sorry for bothering you. I wish you good luck with your studies :)

**Comment by lukasmonk** [comment]
You can have a look at it by downloading the file:
https://drive.google.com/file/d/1qUqyHlMEba5tSWZ4FELfkz3trChLKOAA/view?usp=sharing
unzipping and replacing the program's Code folder.

**Comment by tkozybski** [comment]
It works, thank you! Now if I might use this topic to suggest further changes.
When we import lines from one database to another (Import->Other opening lines), it's comments and engine evaluation doesn't copy and I think it should.
