### ISSUE TITLE
Downloaded installer is on Arabic, looks suspicious

### ISSUE THREAD

**Issue by vidra74** [lukasmonk/lucaschessR#55]
Downloaded installer from SourceForge link and from GitHub. Opening question is on arabic. My Windows are latin, Croatian and UK settings.

![2021-10-02 20_34_25-LucasChess](https://user-images.githubusercontent.com/5217168/135728209-b94010c8-0b12-4a8a-867b-3d6fd60b5665.png)

Looks suspicious. Decided not to install.

**Comment by lukasmonk** [comment]
The windows installer uses Inno Setup and in its configuration it is instructed to use the default language of the system on which it is installed. I have no idea why it has chosen Arabic, probably because it has not found a default language on the system in the relationship it has, and has chosen the first one from its database.
I'll try if it doesn't find one to choose English as the default.
In Spanish:
![image](https://user-images.githubusercontent.com/6254278/135729798-2fe911fd-5e4b-48cf-b526-a8f599a21968.png)

**Comment by lukasmonk** [comment]
Inno Setup:
It searches for a language whose LanguageID setting (normally specified in the [LangOptions] section of the language's .isl file) matches both the primary language identifier and sublanguage identifier of the current user's UI language or locale (depending on the setting of LanguageDetectionMethod).
If no match is found, it searches for just a primary language identifier match. If two or more available languages have the same primary language identifier, it selects the first one listed in the [Languages] section.
Exception: Simplified Chinese is excluded from consideration in this step if the user's UI language or locale (depending on the setting of LanguageDetectionMethod) is Traditional Chinese, and vice versa.
If no match is found, it defaults to the first language specified in the [Languages] section.

And Languages in Lucas Chess Setup begin with Arabian.
I will change it.

**Comment by vidra74** [comment]
Lukas thanks for fast reply.

Maybe you can add ShowLanguageDialog [Setup] section directive. If set to yes (the default), a Select Language dialog will be displayed which gives the user an opportunity to override the language Setup chose. See the [LangOptions] section help topic for details.

**Comment by lukasmonk** [comment]
The ShowLanguageDialog=yes is already in the script. If you click on the option after the arrow, you will get the language selection dialog.
The problem is how to make the first dialog the language dialog.
I haven't found a solution to this.
